# -*- coding: utf-8 -*-
"""tweepy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEVFYm2Trdyoh3aZe20flrUG9tmhgnQq
"""

import tweepy
import json

"""# Autenticación"""

# Commented out IPython magic to ensure Python compatibility.
# %cp drive/MyDrive/MUII-TFM/src/config.py .

# Commented out IPython magic to ensure Python compatibility.
# %load config.py

import config

api_key = config.api_key
api_secret = config.api_secret
access_token = config.access_token
access_token_secret = config.token_secret

auth = tweepy.OAuthHandler(api_key, api_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

"""# Extracción de datos

Obtengo información sobre mi usuario
"""

# My info
data = api.me()
print(json.dumps(data._json, indent=2))

"""Obtengo información de otro usuario"""

# User's info
data_nike = api.get_user("nike")
print(json.dumps(data_nike._json, indent=2))

"""Obtengo los seguidores de un usuario (por defecto sólo salen 20)"""

# Getting followers from user
followers = api.followers(screen_name="nike")
print(len(followers))

"""Obtengo 100 seguidores de un usuario"""

# Getting 100 followers
for user in tweepy.Cursor(api.followers, screen_name="nike").items(100):
  print(json.dumps(user._json, indent=2))

"""Obtengo los seguidos de un usuario"""

# Getting user's followees
for user in tweepy.Cursor(api.friends, screen_name="nike").items(100):
  print(json.dumps(user._json, indent=2))

"""Obtengo el timeline de un usuario"""

# User's timeline
for tweet in tweepy.Cursor(api.user_timeline, screen_name="nike", tweet_mode="extended").items(1):
  print(json.dumps(tweet._json, indent=2))

"""Busco tweets con un query"""

# Searching tweets
for tweet in tweepy.Cursor(api.search, q="twitter", tweet_mode="extended").items(10):
  print(tweet._json["full_text"])